### ISSUE TITLE
Traceback/permission error

### ISSUE THREAD

**Issue by Alasdairbugs** [DuncanRuns/Easy-Multi#10]
Yesterday i had 4 instances open, and when i was finished doing runs, I exited each instance by clicking the X then closed easymulti.

Today, I open the program and I get a traceback error or something relating to 4 files.

![image](https://user-images.githubusercontent.com/41154567/163589639-a58d5f3e-c394-479f-80e2-c7269310e917.png)

I tried uninstalling the program and reinstalling it, but it doesnt appear as a program in windows program manager or whatever, so i tried uninstalling the .exe and I guess that didnt suffice. I can give more details on what i did if needed :)

**Comment by DuncanRuns** [comment]
Looks like easy multi doesn't have access to the options file. Try deleting the options file or running easymulti with admin
![image](https://user-images.githubusercontent.com/59705125/163632447-6a7827e7-3330-4f80-9ef4-dfc62c67f791.png)
