### ISSUE TITLE
scene changing doesnt work in obs for me

### ISSUE THREAD

**Issue by Batsbak13** [DuncanRuns/Easy-Multi#13]
how fix? i have my 1st instance scene on num1 and 2nd instance on num2

**Comment by DuncanRuns** [comment]
There could be various reasons that this does not work
Make sure that if you are using numpad that it actually specifies numpad in the switch to scene keybinds

**Comment by DuncanRuns** [comment]
Assuming this was resolved in some matter, please comment/reopen if you have further issues
