### ISSUE TITLE
antivirus issue

### ISSUE THREAD

**Issue by tildejustin** [DuncanRuns/Easy-Multi#15]
Tried to download 1.5.3 and got this when I ran it.
![image](https://user-images.githubusercontent.com/66330094/187588542-170ef7eb-ff1f-443d-a4b0-03bc38d2721f.png)

**Comment by tildejustin** [comment]
:Hmm: it works fine on my laptop, I'll try again later.

**Comment by DuncanRuns** [comment]
Kinda tired of seeing antivirus stuff
I'll submit the exe to Microsoft as a false positive again

I'm currently rewriting everything in Java where it will just be a runnable jar so this kind of stuff won't happen
