### ISSUE TITLE
F3+ESC and Background Resetting

### ISSUE THREAD

**Issue by DuncanRuns** [DuncanRuns/Easy-Multi#3]
This one I will never do.
It's basically cheating in my opinion and I do not support it.
If someone makes a pull request to add this, I will not accept it.

**Comment by qwertyuioplkjhgfd** [comment]
ok, maybe i understand f3+esc, but how is background resetting cheating? unless you're only referring to f3+esc, which in this case disregard (i would seperate the issues into f3+esc and background resetting if so)

**Comment by DuncanRuns** [comment]
There is a reason I said "in my opinion", I do not have obligation to elaborate.
