### ISSUE TITLE
Instance Freezing and an option to toggle.

### ISSUE THREAD

**Issue by Morni12** [DuncanRuns/Easy-Multi#5]
Will instancefreezing and/or settings change come to this?

**Comment by DuncanRuns** [comment]
Instance freezing is known to be annoying to get working, and dynamicfps works almost as well and is far easier to setup. I will not be looking to do instance freezing.

**Comment by DuncanRuns** [comment]
Had some brain waves, probably gonna do this

**Comment by DuncanRuns** [comment]
SleepBackground should be used instead of instance freezing
