### ISSUE TITLE
Support for Linux

### ISSUE THREAD

**Issue by wurgo** [DuncanRuns/Easy-Multi#7]
I am free to make this work on linux, do you want me to?

**Comment by DuncanRuns** [comment]
Yeah absolutely. I hope the abstractions on top of everything will help with that.

**Comment by wurgo** [comment]
Thanks, that'll help a lot, should I use X?

**Comment by DuncanRuns** [comment]
When writing I thought it was originally going to be a much smaller project, but it got much bigger than expected.
If the project's scope becomes even larger (which I hope it doesn't), I think rewriting EasyMulti.pyw (probably into multiple files) would be necessary.
So a no to the organizing thing for now, that can be left to me.

Also I'm not exactly sure what X is.

**Comment by wurgo** [comment]
That's fair

Also by X I mean Xlib

**Comment by DuncanRuns** [comment]
Xlib looks good
You're probably more qualified than me to make a choice like that

Also I will say that I already use the cross platform `keyboard` module for running the reset macro (pressing not detecting) . I would have used that for everything, but it comes with some major limitations, which is where the custom key_util helps. So looking into the keyboard module could show some useful stuff for making the Linux key_util.

**Comment by wurgo** [comment]
I've decided to use xdotool, a tool for using X via the terminal.
I am using the keyboard module, but only for linux. It's very effective on here but the only downside is that you have to run it with sudo.
I'm actually almost done with the linux version. Is it okay if I make a pr without editing the main file and you can implement them into it? I'm not sure how you structured it KekMan

**Comment by wurgo** [comment]
Also, since the keyboard module is cross-platform, I don't see why you wouldn't use it for everything. Everything you did with the key utils can be done with the keyboard module

**Comment by wurgo** [comment]
You don't have to, but could you add me on Discord? It's much easier to make conversation over there...
Wurgo#1735

**Comment by DuncanRuns** [comment]
Partially done

**Comment by DuncanRuns** [comment]
Should be finished. Waiting on testing to close this issue and release.

**Comment by DuncanRuns** [comment]
yo check this out
https://github.com/woofdoggo/resetti

**Comment by wurgo** [comment]
yeah I seen that in javacord it's sick
