### ISSUE TITLE
Attempt Counter

### ISSUE THREAD

**Issue by SpeedNintendo** [DuncanRuns/Easy-Multi#8]
please output attempt count to a txt file i need my attempt count

**Comment by DuncanRuns** [comment]
Nah but here's an attempts combining script:
https://gist.github.com/DuncanRuns/3d74c0fb7a43e1284f0a1d1ba0474337#file-attemptscounter-py

**Comment by wurgo** [comment]
I might add this

**Comment by DuncanRuns** [comment]
Just had an idea on how to implement this:
World clearing can return what instances is clears worlds from, so easy multi can automatically identify which instances to take the counts from (you would have to reset all instances once or twice for it to know, but I assume that wouldn't take long).

**Comment by wurgo** [comment]
why did you selfassign OMEGA

**Comment by DuncanRuns** [comment]
Because #12 is not the method I want in easy multi.

I want to combine the attempts.txt of the used instances.
I do not want to count how many times the user presses reset.

**Comment by wurgo** [comment]
Why? This is far easier

**Comment by DuncanRuns** [comment]
Far easier does not mean better.
Taking from the instances attempts.txt comes with benefits:
- You don't have to set your own attempts count when you switch to easy multi.
- The attempt counts for different versions are kept separate.

**Comment by wurgo** [comment]
True, sorry, I didn’t think about the version thing :3
